server:
  port: 1226
  servlet:
    context-path: /purepanel

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: purepanel-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/purepanel?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://192.168.80.129:3306/purepanel?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 122699
  data:
    redis:
      database: 0
      #host: localhost
      host: 192.168.80.129
      port: 6379
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

mybatis-plus:
  mapper-locations: classpath*:cn/yzdoit/purepanel/mapper/xml/*Mapper.xml
  global-config:
    banner: false
  configuration:
    log-impl: cn.yzdoit.purepanel.log.MyBatisLogImpl

purepanel:
  res-exception-enabled: true
  #  local-object-store-base-path: /Users/zyan/Documents/dev/srv/purepanel/
  root-user-id: 1948042872317145090
  local-object-store-base-path: C:\Users\bell1\Documents\dev\upload
  login-config:
    single-session-login-enabled: false

logging:
  level:
    cn.yzdoit.purepanel.log.MyBatisLogImpl: trace
    org.springframework.ai.chat.client.advisor: debug